server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:pixdb
    driver-class-name: org.h2.Driver
    username: victor
    password: 123
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
